
//This code has been automatically generated by DudeLabs LLC RCConverter
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Text;
using System.Windows.Forms;

using System.IO;

namespace TransferUniFLEX
{
	/// <summary>
	/// Summary description for frmDialogGetEditor.
	/// </summary>
	public partial class frmDialogGetEditor : System.Windows.Forms.Form
	{
        public string editor = "";
        public bool useExternalEditor = false;
        public bool useInternalEditorTabbedInterface = false;

        public frmDialogGetEditor()
		{
			//
			// Required for Windows Form Designer support
			//
			InitializeComponent();

            //
            // TODO: Add any constructor code after InitializeComponent call
            //
        }

        private void BtnIdok_Click(object sender, EventArgs e)
        {
            editor = txtEditEditor.Text;

            if (checkBoxUseExternalEditor.Checked)     useExternalEditor                = true; else useExternalEditor                = false;
            if (Program.IsDebugBuild())
            {
                if (checkBoxUseInternalEditorTabs.Checked) useInternalEditorTabbedInterface = true; else useInternalEditorTabbedInterface = false;
            }
        }

        private void BtnButtonBrowse_Click(object sender, EventArgs e)
        {
            DialogResult nDlgReturn;
            string strDefaultDir = "";

            if (editor.Length > 0)
                strDefaultDir = Path.GetDirectoryName(editor);

            OpenFileDialog pDlg = new OpenFileDialog();         // CFileDialog pDlg(TRUE, ".exe", NULL, 0, "Executable Files (*.exe) | *.exe||");
            pDlg.Filter = "Executable Files (*.exe) | *.exe||";
            //pDlg.InitialDirectory = strDefaultDir;
            nDlgReturn = pDlg.ShowDialog();

            if (nDlgReturn == DialogResult.OK)
            {
                string cDrivePathName = pDlg.FileName;

                txtEditEditor.Text = cDrivePathName;
            }
        }

        private void FrmDialogGetEditor_Load(object sender, EventArgs e)
        {
            txtEditEditor.Text = editor;
            if (useExternalEditor)
            {
                checkBoxUseExternalEditor.Checked = true;

                checkBoxUseInternalEditorTabs.Visible = false;
                txtEditEditor.Visible = true;
                btnButtonBrowse.Visible = true;
                lblStatic1.Visible = true;
            }
            else
            {
                checkBoxUseExternalEditor.Checked = false;

                checkBoxUseInternalEditorTabs.Top = txtEditEditor.Top + 2;
                checkBoxUseInternalEditorTabs.Left = checkBoxUseExternalEditor.Left;
                txtEditEditor.Visible = false;
                btnButtonBrowse.Visible = false;
                lblStatic1.Visible = false;

                if (Program.IsDebugBuild())
                {
                    checkBoxUseInternalEditorTabs.Visible = true;
                }
            }

            if (useInternalEditorTabbedInterface)
            {
                checkBoxUseInternalEditorTabs.Checked = true;
            }
            else
            {
                checkBoxUseInternalEditorTabs.Checked = false;
            }

            textBoxDescription.Text = "You can use either the embedded editor or an external editor of your choosing. " +
                                      "The embeded editor has the ability to save the edited file back to the virtual " +
                                      "diskette image and the external editor does not. \r\n\r\nWhen saving the file back to the " +
                                      "virtual diskette, a check is made to make sure there is sufficient room for the " +
                                      "new file and that if the file already exists the user is asked if it should be " +
                                      "replaced.";
        }

        private void checkBoxUseExternalEditor_CheckedChanged(object sender, EventArgs e)
        {
            if (checkBoxUseExternalEditor.Checked)
            {
                txtEditEditor.Visible = true;
                btnButtonBrowse.Visible = true;
                lblStatic1.Visible = true;

                checkBoxUseInternalEditorTabs.Visible = false;
            }
            else
            {
                txtEditEditor.Visible = false;
                btnButtonBrowse.Visible = false;
                lblStatic1.Visible = false;

                checkBoxUseInternalEditorTabs.Top = txtEditEditor.Top + 2;
                checkBoxUseInternalEditorTabs.Left = checkBoxUseExternalEditor.Left;

                if (Program.IsDebugBuild())
                    checkBoxUseInternalEditorTabs.Visible = true;
            }
        }
    }
}
