
//This code has been automatically generated by DudeLabs LLC RCConverter
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Text;
using System.Windows.Forms;

namespace TransferUniFLEX
{
	/// <summary>
	/// Summary description for frmDialogOptions.
	/// </summary>
	public partial class frmDialogOptions : System.Windows.Forms.Form
	{
        public bool m_nExpandTabs;
        public bool m_nAddLinefeed;
        public bool m_nCompactBinary;
        public bool m_nStripLinefeed;
        public bool m_nCompressSpaces;
        public bool m_nConvertLfOnly;
        public bool m_nConvertLfOnlyToCrLf;
        public bool m_nConvertLfOnlyToCr;
        public bool useExternalEditor;
        public bool useSystemDatetimeWhenExportingFiles;
        public bool useCreatedDateTimeWhenImporting;
        public bool convertFileNamesToUpperCaseOnImport;

        public string editor;

        bool logFloppyAccess = false;
        string os9FloppyWritesFile = "";
        string os9DefaultISA = "";

        bool   useLastUsedExportDirectory = false;
        bool   useLastUsedImportDirectory = false;
        bool   useExportDirectoryOverride = false;
        bool   useImportDirectoryOverride = false;
        string exportDirectoryOverride     = "";
        string importDirectoryOverride    = "";

        public frmDialogOptions()
		{
			//
			// Required for Windows Form Designer support
			//
			InitializeComponent();

            //
			// TODO: Add any constructor code after InitializeComponent call
			//

            m_nExpandTabs           = Program.GetConfigurationAttribute("Global/TransferUniFLEX/FileExport/ExpandTabs"          , "enabled", "0") == "1" ? true : false;
            m_nAddLinefeed          = Program.GetConfigurationAttribute("Global/TransferUniFLEX/FileExport/AddLinefeed", "enabled", "0") == "1" ? true : false;
            m_nCompactBinary        = Program.GetConfigurationAttribute("Global/TransferUniFLEX/BinaryFile/CompactBinary", "enabled", "0") == "1" ? true : false;
            m_nStripLinefeed        = Program.GetConfigurationAttribute("Global/TransferUniFLEX/FileImport/StripLinefeed", "enabled", "0") == "1" ? true : false;
            m_nCompressSpaces       = Program.GetConfigurationAttribute("Global/TransferUniFLEX/FileImport/CompressSpaces", "enabled", "0") == "1" ? true : false;

            m_nConvertLfOnly        = Program.GetConfigurationAttribute("Global/TransferUniFLEX/FileImport/ConvertLfOnly", "enabled", "0") == "1" ? true : false;
            if (m_nConvertLfOnly)
            {
                m_nConvertLfOnlyToCrLf  = Program.GetConfigurationAttribute("Global/TransferUniFLEX/FileImport/ConvertLfOnlyToCrLf", "enabled", "0") == "1" ? true : false;
                m_nConvertLfOnlyToCr    = Program.GetConfigurationAttribute("Global/TransferUniFLEX/FileImport/ConvertLfOnlyToCr", "enabled", "0") == "1" ? true : false;
            }
            else
            {
                m_nConvertLfOnlyToCrLf  = false;
                m_nConvertLfOnlyToCr    = false;
            }

            checkBoxUseSystemDatetimeWhenExportingFiles.Checked = Program.GetConfigurationAttribute("Global/TransferUniFLEX", "UseSystemDatetimeWhenExportingFiles", "N") == "Y" ? true : false;
            checkBoxUseCreatedDateTimeWhenImporting.Checked = Program.GetConfigurationAttribute("Global/TransferUniFLEX", "UseCreatedDateTimeWhenImporting", "N") == "Y" ? true : false;
            checkBoxConvertFileNamesToUpperCaseOnImport.Checked = Program.GetConfigurationAttribute("Global/TransferUniFLEX", "ConvertFileNamesToUpperCaseOnImport", "N") == "Y" ? true : false;

            checkBoxUseLastUsedExportDirectory.Checked = Program.GetConfigurationAttribute("Global/TransferUniFLEX", "UseLastUsedExportDirectory", "N") == "Y" ? true : false;
            checkBoxUseLastUsedImportDirectory.Checked = Program.GetConfigurationAttribute("Global/TransferUniFLEX", "UseLastUsedImportDirectory", "N") == "Y" ? true : false;

            checkBoxUseExportDirectoryOverride.Checked= Program.GetConfigurationAttribute("Global/TransferUniFLEX", "UseExportOverride", "N") == "Y" ? true : false;
            checkBoxUseImportDirectoryOverride.Checked= Program.GetConfigurationAttribute("Global/TransferUniFLEX", "UseImportOverride", "N") == "Y" ? true : false;
            textBoxExportDirectoryOverride.Text        = Program.GetConfigurationAttribute("Global/TransferUniFLEX", "ExportOverrideDirectory", "");
            textBoxImportDirectoryOverride.Text       = Program.GetConfigurationAttribute("Global/TransferUniFLEX", "ImportOverrideDirectory", "");

            checkBoxLogOS9FileWrites.Checked    = Program.GetConfigurationAttribute("Global/TransferUniFLEX", "LogOS9FloppyWrites", "N") == "Y" ? true : false;
            textBoxLogOS9FileWriteLocation.Text = Program.GetConfigurationAttribute("Global/TransferUniFLEX", "os9FloppyWritesFile", "");
            comboBoxDefaultISA.Text             = Program.GetConfigurationAttribute("Global/TransferUniFLEX", "os9DefaultISA", "8");

            if (!checkBoxUseExportDirectoryOverride.Checked)
                textBoxExportDirectoryOverride.Enabled = false;

            if (!checkBoxUseImportDirectoryOverride.Checked)
                textBoxImportDirectoryOverride.Enabled = false;

            checkBoxDisableTextProcessingDuringExport.Checked = Program.GetConfigurationAttribute("Global/TransferUniFLEX", "DisableTextProcessingDuringExport", "N") == "Y" ? true : false;
            checkBoxDisableTextProcessingDuringImport.Checked = Program.GetConfigurationAttribute("Global/TransferUniFLEX", "DisableTextProcessingDuringImport", "N") == "Y" ? true : false;

            //editor              = Program.GetConfigurationAttribute("Global/TransferUniFLEX", "EditorPath", "");
            //useExternalEditor   = Program.GetConfigurationAttribute("Global/TransferUniFLEX", "UseExternalEditor", "N") == "Y" ? true : false;
        }

        private void ButtonOK_Click(object sender, EventArgs e)
        {
            m_nAddLinefeed        = chkCheckAddLf.Checked;
            m_nCompactBinary      = chkCheckCompactBin.Checked;
            m_nCompressSpaces     = chkCheckCompressSpaces.Checked;
            m_nConvertLfOnlyToCrLf= chkCheckConvertLfOnlyToCrlf.Checked;
            m_nConvertLfOnlyToCr  = chkCheckConvertLfOnlyToCrOnly.Checked;
            m_nExpandTabs         = chkCheckExpandTabs.Checked;
            m_nStripLinefeed      = chkCheckStripLf.Checked;
            m_nConvertLfOnly      = m_nConvertLfOnlyToCrLf || m_nConvertLfOnlyToCr;

            useSystemDatetimeWhenExportingFiles = checkBoxUseSystemDatetimeWhenExportingFiles.Checked;
            useCreatedDateTimeWhenImporting = checkBoxUseCreatedDateTimeWhenImporting.Checked;
            convertFileNamesToUpperCaseOnImport = checkBoxConvertFileNamesToUpperCaseOnImport.Checked;

            useLastUsedExportDirectory = checkBoxUseLastUsedExportDirectory.Checked;
            useLastUsedImportDirectory = checkBoxUseLastUsedImportDirectory.Checked;
            useExportDirectoryOverride = checkBoxUseExportDirectoryOverride.Checked;
            useImportDirectoryOverride = checkBoxUseImportDirectoryOverride.Checked;
            exportDirectoryOverride = textBoxExportDirectoryOverride.Text;
            importDirectoryOverride = textBoxImportDirectoryOverride.Text;

            Program.SaveConfigurationAttribute("Global/TransferUniFLEX/FileExport/ExpandTabs", "enabled", m_nExpandTabs          ? "1" : "0");
            Program.SaveConfigurationAttribute("Global/TransferUniFLEX/FileExport/AddLinefeed", "enabled", m_nAddLinefeed         ? "1" : "0");
            Program.SaveConfigurationAttribute("Global/TransferUniFLEX/BinaryFile/CompactBinary", "enabled", m_nCompactBinary       ? "1" : "0");
            Program.SaveConfigurationAttribute("Global/TransferUniFLEX/FileImport/StripLinefeed", "enabled", m_nStripLinefeed       ? "1" : "0");
            Program.SaveConfigurationAttribute("Global/TransferUniFLEX/FileImport/CompressSpaces", "enabled", m_nCompressSpaces      ? "1" : "0");
            Program.SaveConfigurationAttribute("Global/TransferUniFLEX/FileImport/ConvertLfOnly", "enabled", m_nConvertLfOnly       ? "1" : "0");
            Program.SaveConfigurationAttribute("Global/TransferUniFLEX/FileImport/ConvertLfOnlyToCrLf", "enabled", m_nConvertLfOnlyToCrLf ? "1" : "0");
            Program.SaveConfigurationAttribute("Global/TransferUniFLEX/FileImport/ConvertLfOnlyToCr", "enabled", m_nConvertLfOnlyToCr   ? "1" : "0");

            Program.SaveConfigurationAttribute("Global/TransferUniFLEX", "LogOS9FloppyWrites", checkBoxLogOS9FileWrites.Checked ? "Y" : "N");
            Program.SaveConfigurationAttribute("Global/TransferUniFLEX", "os9FloppyWritesFile", textBoxLogOS9FileWriteLocation.Text);
            Program.SaveConfigurationAttribute("Global/TransferUniFLEX", "os9DefaultISA", comboBoxDefaultISA.Text);

            Program.SaveConfigurationAttribute("Global/TransferUniFLEX", "UseSystemDatetimeWhenExportingFiles", useSystemDatetimeWhenExportingFiles ? "Y" : "N");
            Program.SaveConfigurationAttribute("Global/TransferUniFLEX", "UseCreatedDateTimeWhenImporting", useCreatedDateTimeWhenImporting? "Y" : "N");
            Program.SaveConfigurationAttribute("Global/TransferUniFLEX", "ConvertFileNamesToUpperCaseOnImport", convertFileNamesToUpperCaseOnImport ? "Y" : "N");

            Program.SaveConfigurationAttribute("Global/TransferUniFLEX", "UseLastUsedExportDirectory", useLastUsedExportDirectory ? "Y" : "N");
            Program.SaveConfigurationAttribute("Global/TransferUniFLEX", "UseLastUsedImportDirectory", useLastUsedImportDirectory ? "Y" : "N");

            Program.SaveConfigurationAttribute("Global/TransferUniFLEX", "UseExportOverride", useExportDirectoryOverride ? "Y" : "N");
            Program.SaveConfigurationAttribute("Global/TransferUniFLEX", "UseImportOverride", useImportDirectoryOverride ? "Y" : "N");
            Program.SaveConfigurationAttribute("Global/TransferUniFLEX", "ExportOverrideDirectory", textBoxExportDirectoryOverride.Text);
            Program.SaveConfigurationAttribute("Global/TransferUniFLEX", "ImportOverrideDirectory", textBoxImportDirectoryOverride.Text);

            Program.SaveConfigurationAttribute("Global/TransferUniFLEX", "DisableTextProcessingDuringExport", checkBoxDisableTextProcessingDuringExport.Checked ? "Y" : "N");
            Program.SaveConfigurationAttribute("Global/TransferUniFLEX", "DisableTextProcessingDuringImport", checkBoxDisableTextProcessingDuringImport.Checked ? "Y" : "N");
        }

        private void ButtonCancel_Click(object sender, EventArgs e)
        {

        }

        private void FrmDialogOptions_Load(object sender, EventArgs e)
        {
            chkCheckAddLf.Checked                   = m_nAddLinefeed;
            chkCheckCompactBin.Checked              = m_nCompactBinary;
            chkCheckCompressSpaces.Checked          = m_nCompressSpaces;
            chkCheckConvertLfOnlyToCrlf.Checked     = m_nConvertLfOnlyToCrLf;
            chkCheckConvertLfOnlyToCrOnly.Checked   = m_nConvertLfOnlyToCr;
            chkCheckExpandTabs.Checked              = m_nExpandTabs;
            chkCheckStripLf.Checked                 = m_nStripLinefeed;
        }

        private void buttonBrowseExportDiretory_Click(object sender, EventArgs e)
        {
            var dlg1 = new FolderBrowserDialog();
            dlg1.Description = "Select a folder to extract to:";
            dlg1.ShowNewFolderButton = true;
            dlg1.RootFolder = System.Environment.SpecialFolder.MyComputer;

            // Show the FolderBrowserDialog.
            DialogResult result = dlg1.ShowDialog();
            if (result == DialogResult.OK)
            {
                textBoxExportDirectoryOverride.Text = dlg1.SelectedPath;
            }
        }

        private void buttonBrowseImportDirectory_Click(object sender, EventArgs e)
        {
            var dlg1 = new FolderBrowserDialog();
            dlg1.Description = "Select a folder to extract to:";
            dlg1.ShowNewFolderButton = true;
            dlg1.RootFolder = System.Environment.SpecialFolder.MyComputer;

            // Show the FolderBrowserDialog.
            DialogResult result = dlg1.ShowDialog();
            if (result == DialogResult.OK)
            {
                textBoxImportDirectoryOverride.Text = dlg1.SelectedPath;
            }
        }

        private void checkBoxUseExportDirectoryOverride_CheckedChanged(object sender, EventArgs e)
        {
            if (checkBoxUseExportDirectoryOverride.Checked)
                textBoxExportDirectoryOverride.Enabled = true;
            else
                textBoxExportDirectoryOverride.Enabled = false;
        }

        private void checkBoxUseImportDirectoryOverride_CheckedChanged(object sender, EventArgs e)
        {
            if (checkBoxUseImportDirectoryOverride.Checked)
                textBoxImportDirectoryOverride.Enabled = true;
            else
                textBoxImportDirectoryOverride.Enabled = false;
        }

        private void checkBoxUseLastUsedExportDirectory_CheckedChanged(object sender, EventArgs e)
        {
            if (checkBoxUseLastUsedExportDirectory.Checked)
            {
                // we must disable the override controls

                checkBoxUseExportDirectoryOverride.Checked = false;
                checkBoxUseExportDirectoryOverride.Enabled = false;
            }
            else
            {
                checkBoxUseExportDirectoryOverride.Enabled = true;
            }
        }

        private void checkBoxUseLastUsedImportDirectory_CheckedChanged(object sender, EventArgs e)
        {
            if (checkBoxUseLastUsedImportDirectory.Checked)
            {
                // we must disable the override controls

                checkBoxUseImportDirectoryOverride.Checked = false;
                checkBoxUseImportDirectoryOverride.Enabled = false;
            }
            else
            {
                checkBoxUseImportDirectoryOverride.Enabled = true;
            }
        }
    }
}
