//This code has been automatically generated by DudeLabs, LLC RCConverter
using System;
using System.Drawing;
using System.Collections;
using System.ComponentModel;
using System.Windows.Forms;

namespace TransferUniFLEX
{
    /// <summary>
    /// Summary description for frmDialogGetEditor.
    /// </summary>

    partial class frmDialogGetEditor : System.Windows.Forms.Form
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.Container components = null;
        private System.Windows.Forms.Button btnIdok;
        private System.Windows.Forms.Button btnIdcancel;
        private System.Windows.Forms.Label lblStatic1;
        private System.Windows.Forms.TextBox txtEditEditor;
        private System.Windows.Forms.Button btnButtonBrowse;





        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (components != null)
                {
                    components.Dispose();
                }
            }
            base.Dispose(disposing);
        }

        #region DudeLabs LLC RCConverter generated code
        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.btnIdok = new System.Windows.Forms.Button();
            this.btnIdcancel = new System.Windows.Forms.Button();
            this.lblStatic1 = new System.Windows.Forms.Label();
            this.txtEditEditor = new System.Windows.Forms.TextBox();
            this.btnButtonBrowse = new System.Windows.Forms.Button();
            this.checkBoxUseExternalEditor = new System.Windows.Forms.CheckBox();
            this.textBoxDescription = new System.Windows.Forms.TextBox();
            this.checkBoxUseInternalEditorTabs = new System.Windows.Forms.CheckBox();
            this.SuspendLayout();
            // 
            // btnIdok
            // 
            this.btnIdok.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.btnIdok.DialogResult = System.Windows.Forms.DialogResult.OK;
            this.btnIdok.Location = new System.Drawing.Point(112, 187);
            this.btnIdok.Name = "btnIdok";
            this.btnIdok.Size = new System.Drawing.Size(75, 24);
            this.btnIdok.TabIndex = 1;
            this.btnIdok.Text = "OK";
            this.btnIdok.Click += new System.EventHandler(this.BtnIdok_Click);
            // 
            // btnIdcancel
            // 
            this.btnIdcancel.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.btnIdcancel.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            this.btnIdcancel.Location = new System.Drawing.Point(211, 187);
            this.btnIdcancel.Name = "btnIdcancel";
            this.btnIdcancel.Size = new System.Drawing.Size(75, 24);
            this.btnIdcancel.TabIndex = 2;
            this.btnIdcancel.Text = "Cancel";
            // 
            // lblStatic1
            // 
            this.lblStatic1.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)
            | System.Windows.Forms.AnchorStyles.Right)));
            this.lblStatic1.AutoSize = true;
            this.lblStatic1.Location = new System.Drawing.Point(24, 163);
            this.lblStatic1.Name = "lblStatic1";
            this.lblStatic1.Size = new System.Drawing.Size(357, 13);
            this.lblStatic1.TabIndex = 3;
            this.lblStatic1.Text = "Enter the full path and name to the editor you want to use to open text files";
            // 
            // txtEditEditor
            // 
            this.txtEditEditor.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.txtEditEditor.Location = new System.Drawing.Point(22, 136);
            this.txtEditEditor.Name = "txtEditEditor";
            this.txtEditEditor.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal;
            this.txtEditEditor.Size = new System.Drawing.Size(327, 20);
            this.txtEditEditor.TabIndex = 4;
            // 
            // btnButtonBrowse
            // 
            this.btnButtonBrowse.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.btnButtonBrowse.Location = new System.Drawing.Point(354, 134);
            this.btnButtonBrowse.Name = "btnButtonBrowse";
            this.btnButtonBrowse.Size = new System.Drawing.Size(27, 24);
            this.btnButtonBrowse.TabIndex = 5;
            this.btnButtonBrowse.Text = "...";
            this.btnButtonBrowse.Click += new System.EventHandler(this.BtnButtonBrowse_Click);
            // 
            // checkBoxUseExternalEditor
            // 
            this.checkBoxUseExternalEditor.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.checkBoxUseExternalEditor.AutoSize = true;
            this.checkBoxUseExternalEditor.Location = new System.Drawing.Point(22, 113);
            this.checkBoxUseExternalEditor.Name = "checkBoxUseExternalEditor";
            this.checkBoxUseExternalEditor.Size = new System.Drawing.Size(116, 17);
            this.checkBoxUseExternalEditor.TabIndex = 6;
            this.checkBoxUseExternalEditor.Text = "Use External Editor";
            this.checkBoxUseExternalEditor.UseVisualStyleBackColor = true;
            this.checkBoxUseExternalEditor.CheckedChanged += new System.EventHandler(this.checkBoxUseExternalEditor_CheckedChanged);
            // 
            // textBoxDescription
            // 
            this.textBoxDescription.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBoxDescription.Enabled = false;
            this.textBoxDescription.Location = new System.Drawing.Point(22, 12);
            this.textBoxDescription.Multiline = true;
            this.textBoxDescription.Name = "textBoxDescription";
            this.textBoxDescription.ReadOnly = true;
            this.textBoxDescription.Size = new System.Drawing.Size(356, 93);
            this.textBoxDescription.TabIndex = 7;
            // 
            // checkBoxUseInternalEditorTabs
            // 
            this.checkBoxUseInternalEditorTabs.AutoSize = true;
            this.checkBoxUseInternalEditorTabs.Location = new System.Drawing.Point(100, 217);
            this.checkBoxUseInternalEditorTabs.Name = "checkBoxUseInternalEditorTabs";
            this.checkBoxUseInternalEditorTabs.Size = new System.Drawing.Size(202, 17);
            this.checkBoxUseInternalEditorTabs.TabIndex = 8;
            this.checkBoxUseInternalEditorTabs.Text = "Use tabbed interface in internal editor";
            this.checkBoxUseInternalEditorTabs.UseVisualStyleBackColor = true;
            this.checkBoxUseInternalEditorTabs.Visible = false;
            // 
            // frmDialogGetEditor
            // 
            this.AcceptButton = this.btnIdok;
            this.ClientSize = new System.Drawing.Size(398, 229);
            this.Controls.Add(this.checkBoxUseInternalEditorTabs);
            this.Controls.Add(this.textBoxDescription);
            this.Controls.Add(this.checkBoxUseExternalEditor);
            this.Controls.Add(this.btnButtonBrowse);
            this.Controls.Add(this.btnIdcancel);
            this.Controls.Add(this.btnIdok);
            this.Controls.Add(this.lblStatic1);
            this.Controls.Add(this.txtEditEditor);
            this.Font = new System.Drawing.Font("Microsoft Sans Serif", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.Name = "frmDialogGetEditor";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.Text = "Select Editor Program";
            this.Load += new System.EventHandler(this.FrmDialogGetEditor_Load);
            this.ResumeLayout(false);
            this.PerformLayout();

        }
        #endregion

        private CheckBox checkBoxUseExternalEditor;
        private TextBox textBoxDescription;
        private CheckBox checkBoxUseInternalEditorTabs;
    }
}
