//This code has been automatically generated by DudeLabs, LLC RCConverter
using System;
using System.Drawing;
using System.Collections;
using System.ComponentModel;
using System.Windows.Forms;

namespace TransferUniFLEX
{
    /// <summary>
    /// Summary description for frmDialogOptions.
    /// </summary>

    partial class frmDialogOptions : System.Windows.Forms.Form
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.Container components = null;
        private System.Windows.Forms.GroupBox grpStatic1;
        private System.Windows.Forms.GroupBox grpStatic2;
        private System.Windows.Forms.CheckBox chkCheckAddLf;
        private System.Windows.Forms.CheckBox chkCheckExpandTabs;
        private System.Windows.Forms.CheckBox chkCheckCompactBin;
        private System.Windows.Forms.GroupBox grpStatic3;
        private System.Windows.Forms.GroupBox grpStatic4;
        private System.Windows.Forms.CheckBox chkCheckStripLf;
        private System.Windows.Forms.CheckBox chkCheckCompressSpaces;
        private System.Windows.Forms.GroupBox grpStatic5;
        private System.Windows.Forms.CheckBox chkCheckConvertLfOnlyToCrOnly;
        private System.Windows.Forms.CheckBox chkCheckConvertLfOnlyToCrlf;





        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (components != null)
                {
                    components.Dispose();
                }
            }
            base.Dispose(disposing);
        }

        #region DudeLabs LLC RCConverter generated code
        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.grpStatic1 = new System.Windows.Forms.GroupBox();
            this.grpStatic2 = new System.Windows.Forms.GroupBox();
            this.checkBoxDisableTextProcessingDuringExport = new System.Windows.Forms.CheckBox();
            this.textBoxExportDirectoryOverride = new System.Windows.Forms.TextBox();
            this.checkBoxUseLastUsedExportDirectory = new System.Windows.Forms.CheckBox();
            this.buttonBrowseExportDiretory = new System.Windows.Forms.Button();
            this.checkBoxUseExportDirectoryOverride = new System.Windows.Forms.CheckBox();
            this.chkCheckAddLf = new System.Windows.Forms.CheckBox();
            this.chkCheckExpandTabs = new System.Windows.Forms.CheckBox();
            this.grpStatic4 = new System.Windows.Forms.GroupBox();
            this.checkBoxDisableTextProcessingDuringImport = new System.Windows.Forms.CheckBox();
            this.checkBoxUseLastUsedImportDirectory = new System.Windows.Forms.CheckBox();
            this.buttonBrowseImportDirectory = new System.Windows.Forms.Button();
            this.textBoxImportDirectoryOverride = new System.Windows.Forms.TextBox();
            this.checkBoxUseImportDirectoryOverride = new System.Windows.Forms.CheckBox();
            this.chkCheckCompressSpaces = new System.Windows.Forms.CheckBox();
            this.chkCheckConvertLfOnlyToCrlf = new System.Windows.Forms.CheckBox();
            this.chkCheckConvertLfOnlyToCrOnly = new System.Windows.Forms.CheckBox();
            this.chkCheckStripLf = new System.Windows.Forms.CheckBox();
            this.chkCheckCompactBin = new System.Windows.Forms.CheckBox();
            this.grpStatic3 = new System.Windows.Forms.GroupBox();
            this.checkBoxUseCreatedDateTimeWhenImporting = new System.Windows.Forms.CheckBox();
            this.checkBoxUseSystemDatetimeWhenExportingFiles = new System.Windows.Forms.CheckBox();
            this.groupBoxOS9SpecificOptions = new System.Windows.Forms.GroupBox();
            this.comboBoxDefaultISA = new System.Windows.Forms.ComboBox();
            this.labelDefaultISA = new System.Windows.Forms.Label();
            this.textBoxLogOS9FileWriteLocation = new System.Windows.Forms.TextBox();
            this.checkBoxLogOS9FileWrites = new System.Windows.Forms.CheckBox();
            this.grpStatic5 = new System.Windows.Forms.GroupBox();
            this.buttonOK = new System.Windows.Forms.Button();
            this.buttonCancel = new System.Windows.Forms.Button();
            this.checkBoxConvertFileNamesToUpperCaseOnImport = new System.Windows.Forms.CheckBox();
            this.grpStatic1.SuspendLayout();
            this.grpStatic2.SuspendLayout();
            this.grpStatic4.SuspendLayout();
            this.grpStatic3.SuspendLayout();
            this.groupBoxOS9SpecificOptions.SuspendLayout();
            this.grpStatic5.SuspendLayout();
            this.SuspendLayout();
            // 
            // grpStatic1
            // 
            this.grpStatic1.Controls.Add(this.grpStatic2);
            this.grpStatic1.Controls.Add(this.grpStatic4);
            this.grpStatic1.Location = new System.Drawing.Point(16, 16);
            this.grpStatic1.Name = "grpStatic1";
            this.grpStatic1.Size = new System.Drawing.Size(474, 252);
            this.grpStatic1.TabIndex = 0;
            this.grpStatic1.TabStop = false;
            this.grpStatic1.Text = "Text File Processing Options";
            // 
            // grpStatic2
            // 
            this.grpStatic2.Controls.Add(this.checkBoxDisableTextProcessingDuringExport);
            this.grpStatic2.Controls.Add(this.textBoxExportDirectoryOverride);
            this.grpStatic2.Controls.Add(this.checkBoxUseLastUsedExportDirectory);
            this.grpStatic2.Controls.Add(this.buttonBrowseExportDiretory);
            this.grpStatic2.Controls.Add(this.checkBoxUseExportDirectoryOverride);
            this.grpStatic2.Controls.Add(this.chkCheckAddLf);
            this.grpStatic2.Controls.Add(this.chkCheckExpandTabs);
            this.grpStatic2.Location = new System.Drawing.Point(14, 27);
            this.grpStatic2.Name = "grpStatic2";
            this.grpStatic2.Size = new System.Drawing.Size(210, 220);
            this.grpStatic2.TabIndex = 0;
            this.grpStatic2.TabStop = false;
            this.grpStatic2.Text = "Export Options";
            // 
            // checkBoxDisableTextProcessingDuringExport
            // 
            this.checkBoxDisableTextProcessingDuringExport.AutoSize = true;
            this.checkBoxDisableTextProcessingDuringExport.Location = new System.Drawing.Point(24, 197);
            this.checkBoxDisableTextProcessingDuringExport.Name = "checkBoxDisableTextProcessingDuringExport";
            this.checkBoxDisableTextProcessingDuringExport.Size = new System.Drawing.Size(140, 17);
            this.checkBoxDisableTextProcessingDuringExport.TabIndex = 6;
            this.checkBoxDisableTextProcessingDuringExport.Text = "Disable Text Processing";
            this.checkBoxDisableTextProcessingDuringExport.UseVisualStyleBackColor = true;
            // 
            // textBoxExportDirectoryOverride
            // 
            this.textBoxExportDirectoryOverride.Location = new System.Drawing.Point(24, 142);
            this.textBoxExportDirectoryOverride.Name = "textBoxExportDirectoryOverride";
            this.textBoxExportDirectoryOverride.Size = new System.Drawing.Size(136, 20);
            this.textBoxExportDirectoryOverride.TabIndex = 3;
            // 
            // checkBoxUseLastUsedExportDirectory
            // 
            this.checkBoxUseLastUsedExportDirectory.AutoSize = true;
            this.checkBoxUseLastUsedExportDirectory.Location = new System.Drawing.Point(24, 177);
            this.checkBoxUseLastUsedExportDirectory.Name = "checkBoxUseLastUsedExportDirectory";
            this.checkBoxUseLastUsedExportDirectory.Size = new System.Drawing.Size(180, 17);
            this.checkBoxUseLastUsedExportDirectory.TabIndex = 5;
            this.checkBoxUseLastUsedExportDirectory.Text = "Use last used directory for export";
            this.checkBoxUseLastUsedExportDirectory.UseVisualStyleBackColor = true;
            this.checkBoxUseLastUsedExportDirectory.CheckedChanged += new System.EventHandler(this.checkBoxUseLastUsedExportDirectory_CheckedChanged);
            // 
            // buttonBrowseExportDiretory
            // 
            this.buttonBrowseExportDiretory.Location = new System.Drawing.Point(166, 141);
            this.buttonBrowseExportDiretory.Name = "buttonBrowseExportDiretory";
            this.buttonBrowseExportDiretory.Size = new System.Drawing.Size(38, 23);
            this.buttonBrowseExportDiretory.TabIndex = 4;
            this.buttonBrowseExportDiretory.Text = "...";
            this.buttonBrowseExportDiretory.UseVisualStyleBackColor = true;
            this.buttonBrowseExportDiretory.Click += new System.EventHandler(this.buttonBrowseExportDiretory_Click);
            // 
            // checkBoxUseExportDirectoryOverride
            // 
            this.checkBoxUseExportDirectoryOverride.AutoSize = true;
            this.checkBoxUseExportDirectoryOverride.Location = new System.Drawing.Point(24, 118);
            this.checkBoxUseExportDirectoryOverride.Name = "checkBoxUseExportDirectoryOverride";
            this.checkBoxUseExportDirectoryOverride.Size = new System.Drawing.Size(166, 17);
            this.checkBoxUseExportDirectoryOverride.TabIndex = 2;
            this.checkBoxUseExportDirectoryOverride.Text = "Use Export Directory Override";
            this.checkBoxUseExportDirectoryOverride.UseVisualStyleBackColor = true;
            this.checkBoxUseExportDirectoryOverride.CheckedChanged += new System.EventHandler(this.checkBoxUseExportDirectoryOverride_CheckedChanged);
            // 
            // chkCheckAddLf
            // 
            this.chkCheckAddLf.Location = new System.Drawing.Point(24, 26);
            this.chkCheckAddLf.Name = "chkCheckAddLf";
            this.chkCheckAddLf.Size = new System.Drawing.Size(164, 17);
            this.chkCheckAddLf.TabIndex = 0;
            this.chkCheckAddLf.Text = "Add Linefeeds during Export";
            // 
            // chkCheckExpandTabs
            // 
            this.chkCheckExpandTabs.Location = new System.Drawing.Point(24, 47);
            this.chkCheckExpandTabs.Name = "chkCheckExpandTabs";
            this.chkCheckExpandTabs.Size = new System.Drawing.Size(158, 17);
            this.chkCheckExpandTabs.TabIndex = 1;
            this.chkCheckExpandTabs.Text = "Expand Tabs during Export";
            // 
            // grpStatic4
            // 
            this.grpStatic4.Controls.Add(this.checkBoxDisableTextProcessingDuringImport);
            this.grpStatic4.Controls.Add(this.checkBoxUseLastUsedImportDirectory);
            this.grpStatic4.Controls.Add(this.buttonBrowseImportDirectory);
            this.grpStatic4.Controls.Add(this.textBoxImportDirectoryOverride);
            this.grpStatic4.Controls.Add(this.checkBoxUseImportDirectoryOverride);
            this.grpStatic4.Controls.Add(this.chkCheckCompressSpaces);
            this.grpStatic4.Controls.Add(this.chkCheckConvertLfOnlyToCrlf);
            this.grpStatic4.Controls.Add(this.chkCheckConvertLfOnlyToCrOnly);
            this.grpStatic4.Controls.Add(this.chkCheckStripLf);
            this.grpStatic4.Location = new System.Drawing.Point(241, 27);
            this.grpStatic4.Name = "grpStatic4";
            this.grpStatic4.Size = new System.Drawing.Size(210, 220);
            this.grpStatic4.TabIndex = 1;
            this.grpStatic4.TabStop = false;
            this.grpStatic4.Text = "Import Options";
            // 
            // checkBoxDisableTextProcessingDuringImport
            // 
            this.checkBoxDisableTextProcessingDuringImport.AutoSize = true;
            this.checkBoxDisableTextProcessingDuringImport.Location = new System.Drawing.Point(21, 197);
            this.checkBoxDisableTextProcessingDuringImport.Name = "checkBoxDisableTextProcessingDuringImport";
            this.checkBoxDisableTextProcessingDuringImport.Size = new System.Drawing.Size(140, 17);
            this.checkBoxDisableTextProcessingDuringImport.TabIndex = 0;
            this.checkBoxDisableTextProcessingDuringImport.Text = "Disable Text Processing";
            this.checkBoxDisableTextProcessingDuringImport.UseVisualStyleBackColor = true;
            // 
            // checkBoxUseLastUsedImportDirectory
            // 
            this.checkBoxUseLastUsedImportDirectory.AutoSize = true;
            this.checkBoxUseLastUsedImportDirectory.Location = new System.Drawing.Point(21, 177);
            this.checkBoxUseLastUsedImportDirectory.Name = "checkBoxUseLastUsedImportDirectory";
            this.checkBoxUseLastUsedImportDirectory.Size = new System.Drawing.Size(179, 17);
            this.checkBoxUseLastUsedImportDirectory.TabIndex = 8;
            this.checkBoxUseLastUsedImportDirectory.Text = "Use last used directory for import";
            this.checkBoxUseLastUsedImportDirectory.UseVisualStyleBackColor = true;
            this.checkBoxUseLastUsedImportDirectory.CheckedChanged += new System.EventHandler(this.checkBoxUseLastUsedImportDirectory_CheckedChanged);
            // 
            // buttonBrowseImportDirectory
            // 
            this.buttonBrowseImportDirectory.Location = new System.Drawing.Point(164, 141);
            this.buttonBrowseImportDirectory.Name = "buttonBrowseImportDirectory";
            this.buttonBrowseImportDirectory.Size = new System.Drawing.Size(35, 23);
            this.buttonBrowseImportDirectory.TabIndex = 7;
            this.buttonBrowseImportDirectory.Text = "...";
            this.buttonBrowseImportDirectory.UseVisualStyleBackColor = true;
            this.buttonBrowseImportDirectory.Click += new System.EventHandler(this.buttonBrowseImportDirectory_Click);
            // 
            // textBoxImportDirectoryOverride
            // 
            this.textBoxImportDirectoryOverride.Location = new System.Drawing.Point(21, 142);
            this.textBoxImportDirectoryOverride.Name = "textBoxImportDirectoryOverride";
            this.textBoxImportDirectoryOverride.Size = new System.Drawing.Size(136, 20);
            this.textBoxImportDirectoryOverride.TabIndex = 6;
            // 
            // checkBoxUseImportDirectoryOverride
            // 
            this.checkBoxUseImportDirectoryOverride.AutoSize = true;
            this.checkBoxUseImportDirectoryOverride.Location = new System.Drawing.Point(21, 118);
            this.checkBoxUseImportDirectoryOverride.Name = "checkBoxUseImportDirectoryOverride";
            this.checkBoxUseImportDirectoryOverride.Size = new System.Drawing.Size(165, 17);
            this.checkBoxUseImportDirectoryOverride.TabIndex = 4;
            this.checkBoxUseImportDirectoryOverride.Text = "Use Import Directory Override";
            this.checkBoxUseImportDirectoryOverride.UseVisualStyleBackColor = true;
            this.checkBoxUseImportDirectoryOverride.CheckedChanged += new System.EventHandler(this.checkBoxUseImportDirectoryOverride_CheckedChanged);
            // 
            // chkCheckCompressSpaces
            // 
            this.chkCheckCompressSpaces.Location = new System.Drawing.Point(21, 47);
            this.chkCheckCompressSpaces.Name = "chkCheckCompressSpaces";
            this.chkCheckCompressSpaces.Size = new System.Drawing.Size(178, 17);
            this.chkCheckCompressSpaces.TabIndex = 1;
            this.chkCheckCompressSpaces.Text = "Compress Spaces during Import";
            // 
            // chkCheckConvertLfOnlyToCrlf
            // 
            this.chkCheckConvertLfOnlyToCrlf.Location = new System.Drawing.Point(21, 88);
            this.chkCheckConvertLfOnlyToCrlf.Name = "chkCheckConvertLfOnlyToCrlf";
            this.chkCheckConvertLfOnlyToCrlf.Size = new System.Drawing.Size(176, 17);
            this.chkCheckConvertLfOnlyToCrlf.TabIndex = 3;
            this.chkCheckConvertLfOnlyToCrlf.Text = "Convert LF Only to CR/LF";
            // 
            // chkCheckConvertLfOnlyToCrOnly
            // 
            this.chkCheckConvertLfOnlyToCrOnly.Location = new System.Drawing.Point(21, 68);
            this.chkCheckConvertLfOnlyToCrOnly.Name = "chkCheckConvertLfOnlyToCrOnly";
            this.chkCheckConvertLfOnlyToCrOnly.Size = new System.Drawing.Size(156, 17);
            this.chkCheckConvertLfOnlyToCrOnly.TabIndex = 2;
            this.chkCheckConvertLfOnlyToCrOnly.Text = "Convert LF only to CR only";
            // 
            // chkCheckStripLf
            // 
            this.chkCheckStripLf.Location = new System.Drawing.Point(21, 26);
            this.chkCheckStripLf.Name = "chkCheckStripLf";
            this.chkCheckStripLf.Size = new System.Drawing.Size(164, 17);
            this.chkCheckStripLf.TabIndex = 0;
            this.chkCheckStripLf.Text = "Strip Linefeeds during Import";
            // 
            // chkCheckCompactBin
            // 
            this.chkCheckCompactBin.Location = new System.Drawing.Point(19, 20);
            this.chkCheckCompactBin.Name = "chkCheckCompactBin";
            this.chkCheckCompactBin.Size = new System.Drawing.Size(226, 17);
            this.chkCheckCompactBin.TabIndex = 0;
            this.chkCheckCompactBin.Text = "Compact Binary Files during Import/Export";
            // 
            // grpStatic3
            // 
            this.grpStatic3.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)));
            this.grpStatic3.Controls.Add(this.checkBoxConvertFileNamesToUpperCaseOnImport);
            this.grpStatic3.Controls.Add(this.checkBoxUseCreatedDateTimeWhenImporting);
            this.grpStatic3.Controls.Add(this.checkBoxUseSystemDatetimeWhenExportingFiles);
            this.grpStatic3.Controls.Add(this.groupBoxOS9SpecificOptions);
            this.grpStatic3.Controls.Add(this.grpStatic1);
            this.grpStatic3.Controls.Add(this.grpStatic5);
            this.grpStatic3.Location = new System.Drawing.Point(10, 11);
            this.grpStatic3.Name = "grpStatic3";
            this.grpStatic3.Size = new System.Drawing.Size(513, 480);
            this.grpStatic3.TabIndex = 8;
            this.grpStatic3.TabStop = false;
            // 
            // checkBoxUseCreatedDateTimeWhenImporting
            // 
            this.checkBoxUseCreatedDateTimeWhenImporting.AutoSize = true;
            this.checkBoxUseCreatedDateTimeWhenImporting.Location = new System.Drawing.Point(35, 303);
            this.checkBoxUseCreatedDateTimeWhenImporting.Name = "checkBoxUseCreatedDateTimeWhenImporting";
            this.checkBoxUseCreatedDateTimeWhenImporting.Size = new System.Drawing.Size(389, 17);
            this.checkBoxUseCreatedDateTimeWhenImporting.TabIndex = 2;
            this.checkBoxUseCreatedDateTimeWhenImporting.Text = "Use Created Date Time When Importing (as opposed  to Modified Date Time)";
            this.checkBoxUseCreatedDateTimeWhenImporting.UseVisualStyleBackColor = true;
            // 
            // checkBoxUseSystemDatetimeWhenExportingFiles
            // 
            this.checkBoxUseSystemDatetimeWhenExportingFiles.AutoSize = true;
            this.checkBoxUseSystemDatetimeWhenExportingFiles.Location = new System.Drawing.Point(35, 280);
            this.checkBoxUseSystemDatetimeWhenExportingFiles.Name = "checkBoxUseSystemDatetimeWhenExportingFiles";
            this.checkBoxUseSystemDatetimeWhenExportingFiles.Size = new System.Drawing.Size(258, 17);
            this.checkBoxUseSystemDatetimeWhenExportingFiles.TabIndex = 1;
            this.checkBoxUseSystemDatetimeWhenExportingFiles.Text = "Use System Date and Time When Exporting Files";
            this.checkBoxUseSystemDatetimeWhenExportingFiles.UseVisualStyleBackColor = true;
            // 
            // groupBoxOS9SpecificOptions
            // 
            this.groupBoxOS9SpecificOptions.Controls.Add(this.comboBoxDefaultISA);
            this.groupBoxOS9SpecificOptions.Controls.Add(this.labelDefaultISA);
            this.groupBoxOS9SpecificOptions.Controls.Add(this.textBoxLogOS9FileWriteLocation);
            this.groupBoxOS9SpecificOptions.Controls.Add(this.checkBoxLogOS9FileWrites);
            this.groupBoxOS9SpecificOptions.Location = new System.Drawing.Point(16, 410);
            this.groupBoxOS9SpecificOptions.Name = "groupBoxOS9SpecificOptions";
            this.groupBoxOS9SpecificOptions.Size = new System.Drawing.Size(474, 79);
            this.groupBoxOS9SpecificOptions.TabIndex = 5;
            this.groupBoxOS9SpecificOptions.TabStop = false;
            this.groupBoxOS9SpecificOptions.Text = "OS-9 Specific Options";
            // 
            // comboBoxDefaultISA
            // 
            this.comboBoxDefaultISA.FormattingEnabled = true;
            this.comboBoxDefaultISA.Items.AddRange(new object[] {
            "1",
            "2",
            "4",
            "8",
            "16"});
            this.comboBoxDefaultISA.Location = new System.Drawing.Point(286, 47);
            this.comboBoxDefaultISA.Name = "comboBoxDefaultISA";
            this.comboBoxDefaultISA.Size = new System.Drawing.Size(48, 21);
            this.comboBoxDefaultISA.TabIndex = 3;
            // 
            // labelDefaultISA
            // 
            this.labelDefaultISA.AutoSize = true;
            this.labelDefaultISA.Location = new System.Drawing.Point(19, 51);
            this.labelDefaultISA.Name = "labelDefaultISA";
            this.labelDefaultISA.Size = new System.Drawing.Size(258, 13);
            this.labelDefaultISA.TabIndex = 2;
            this.labelDefaultISA.Text = "Default ISA Value for Directories (must be power of 2)";
            // 
            // textBoxLogOS9FileWriteLocation
            // 
            this.textBoxLogOS9FileWriteLocation.Location = new System.Drawing.Point(153, 19);
            this.textBoxLogOS9FileWriteLocation.Name = "textBoxLogOS9FileWriteLocation";
            this.textBoxLogOS9FileWriteLocation.Size = new System.Drawing.Size(299, 20);
            this.textBoxLogOS9FileWriteLocation.TabIndex = 1;
            this.textBoxLogOS9FileWriteLocation.Text = "D:\\OS9FloppyDIskWrites.txt";
            // 
            // checkBoxLogOS9FileWrites
            // 
            this.checkBoxLogOS9FileWrites.AutoSize = true;
            this.checkBoxLogOS9FileWrites.Location = new System.Drawing.Point(19, 20);
            this.checkBoxLogOS9FileWrites.Name = "checkBoxLogOS9FileWrites";
            this.checkBoxLogOS9FileWrites.Size = new System.Drawing.Size(114, 17);
            this.checkBoxLogOS9FileWrites.TabIndex = 0;
            this.checkBoxLogOS9FileWrites.Text = "Log OS9 file writes";
            this.checkBoxLogOS9FileWrites.UseVisualStyleBackColor = true;
            // 
            // grpStatic5
            // 
            this.grpStatic5.Controls.Add(this.chkCheckCompactBin);
            this.grpStatic5.Location = new System.Drawing.Point(16, 355);
            this.grpStatic5.Name = "grpStatic5";
            this.grpStatic5.Size = new System.Drawing.Size(474, 45);
            this.grpStatic5.TabIndex = 4;
            this.grpStatic5.TabStop = false;
            this.grpStatic5.Text = "Binary File Processing Options";
            // 
            // buttonOK
            // 
            this.buttonOK.Anchor = System.Windows.Forms.AnchorStyles.Bottom;
            this.buttonOK.DialogResult = System.Windows.Forms.DialogResult.OK;
            this.buttonOK.Location = new System.Drawing.Point(178, 506);
            this.buttonOK.Name = "buttonOK";
            this.buttonOK.Size = new System.Drawing.Size(75, 23);
            this.buttonOK.TabIndex = 0;
            this.buttonOK.Text = "&OK";
            this.buttonOK.UseVisualStyleBackColor = true;
            this.buttonOK.Click += new System.EventHandler(this.ButtonOK_Click);
            // 
            // buttonCancel
            // 
            this.buttonCancel.Anchor = System.Windows.Forms.AnchorStyles.Bottom;
            this.buttonCancel.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            this.buttonCancel.Location = new System.Drawing.Point(267, 506);
            this.buttonCancel.Name = "buttonCancel";
            this.buttonCancel.Size = new System.Drawing.Size(75, 23);
            this.buttonCancel.TabIndex = 1;
            this.buttonCancel.Text = "&Cancel";
            this.buttonCancel.UseVisualStyleBackColor = true;
            this.buttonCancel.Click += new System.EventHandler(this.ButtonCancel_Click);
            // 
            // checkBoxConvertFileNamesToUpperCaseOnImport
            // 
            this.checkBoxConvertFileNamesToUpperCaseOnImport.AutoSize = true;
            this.checkBoxConvertFileNamesToUpperCaseOnImport.Location = new System.Drawing.Point(35, 323);
            this.checkBoxConvertFileNamesToUpperCaseOnImport.Name = "checkBoxConvertFileNamesToUpperCaseOnImport";
            this.checkBoxConvertFileNamesToUpperCaseOnImport.Size = new System.Drawing.Size(236, 17);
            this.checkBoxConvertFileNamesToUpperCaseOnImport.TabIndex = 3;
            this.checkBoxConvertFileNamesToUpperCaseOnImport.Text = "Convert File Names to Upper Case on Import";
            this.checkBoxConvertFileNamesToUpperCaseOnImport.UseVisualStyleBackColor = true;
            // 
            // frmDialogOptions
            // 
            this.ClientSize = new System.Drawing.Size(542, 540);
            this.Controls.Add(this.buttonCancel);
            this.Controls.Add(this.buttonOK);
            this.Controls.Add(this.grpStatic3);
            this.Font = new System.Drawing.Font("Microsoft Sans Serif", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.Name = "frmDialogOptions";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.Text = "Configuration Options";
            this.Load += new System.EventHandler(this.FrmDialogOptions_Load);
            this.grpStatic1.ResumeLayout(false);
            this.grpStatic2.ResumeLayout(false);
            this.grpStatic2.PerformLayout();
            this.grpStatic4.ResumeLayout(false);
            this.grpStatic4.PerformLayout();
            this.grpStatic3.ResumeLayout(false);
            this.grpStatic3.PerformLayout();
            this.groupBoxOS9SpecificOptions.ResumeLayout(false);
            this.groupBoxOS9SpecificOptions.PerformLayout();
            this.grpStatic5.ResumeLayout(false);
            this.ResumeLayout(false);

        }
        #endregion

        private Button buttonOK;
        private Button buttonCancel;
        private TextBox textBoxLogOS9FileWriteLocation;
        private CheckBox checkBoxLogOS9FileWrites;
        private GroupBox groupBoxOS9SpecificOptions;
        private ComboBox comboBoxDefaultISA;
        private Label labelDefaultISA;
        private Button buttonBrowseExportDiretory;
        private CheckBox checkBoxUseExportDirectoryOverride;
        private Button buttonBrowseImportDirectory;
        private TextBox textBoxImportDirectoryOverride;
        private CheckBox checkBoxUseImportDirectoryOverride;
        private CheckBox checkBoxUseLastUsedExportDirectory;
        private CheckBox checkBoxUseLastUsedImportDirectory;
        private TextBox textBoxExportDirectoryOverride;
        private CheckBox checkBoxUseSystemDatetimeWhenExportingFiles;
        private CheckBox checkBoxUseCreatedDateTimeWhenImporting;
        private CheckBox checkBoxDisableTextProcessingDuringExport;
        private CheckBox checkBoxDisableTextProcessingDuringImport;
        private CheckBox checkBoxConvertFileNamesToUpperCaseOnImport;
    }
}
